package signature

import "fmt"

// Envelope provides functions to basic functions to manipulate signatures
type Envelope interface {
	// Sign generates and sign the envelope according to the sign request.
	Sign(req *SignRequest) ([]byte, error)

	// Verify verifies the envelope and returns its enclosed payload and signer
	// info.
	Verify() (*Payload, *SignerInfo, error)

	// Payload returns the payload of the envelope.
	// Payload is trusted only after the successful call to `Verify()`.
	Payload() (*Payload, error)

	// SignerInfo returns the signer information of the envelope.
	// SignerInfo is trusted only after the successful call to `Verify()`.
	SignerInfo() (*SignerInfo, error)
}

// NewEnvelopeFunc defines a function to create a new Envelope
type NewEnvelopeFunc func() Envelope

// ParseEnvelopeFunc defines a function to create a new Envelope with given
// envelope bytes
type ParseEnvelopeFunc func([]byte) (Envelope, error)

type envelopeFunc struct {
	newFunc   NewEnvelopeFunc
	parseFunc ParseEnvelopeFunc
}

var envelopeFuncs = make(map[string]envelopeFunc)

// RegisterEnvelopeType registers newFunc and parseFunc for the given mediaType
// Thoese functions are intended to be called when creating a new envelope
func RegisterEnvelopeType(mediaType string, newFunc NewEnvelopeFunc, parseFunc ParseEnvelopeFunc) error {
	if newFunc == nil || parseFunc == nil {
		return fmt.Errorf("required functions not provided")
	}

	envelopeFuncs[mediaType] = envelopeFunc{
		newFunc:   newFunc,
		parseFunc: parseFunc,
	}
	return nil
}

// RegisteredEnvelopeTypes lists registered envelope media types.
func RegisteredEnvelopeTypes() []string {
	types := []string{}

	for envelopeType := range envelopeFuncs {
		types = append(types, envelopeType)
	}

	return types
}

// NewEnvelope returns an envelope of given media type
func NewEnvelope(mediaType string) (Envelope, error) {
	envelopeFunc, ok := envelopeFuncs[mediaType]
	if !ok {
		return nil, &UnsupportedSignatureFormatError{MediaType: mediaType}
	}
	return envelopeFunc.newFunc(), nil
}

// NewEnvelope returns an envelope generated by given bytes and media type
func ParseEnvelope(mediaType string, envelopeBytes []byte) (Envelope, error) {
	envelopeFunc, ok := envelopeFuncs[mediaType]
	if !ok {
		return nil, &UnsupportedSignatureFormatError{MediaType: mediaType}
	}
	return envelopeFunc.parseFunc(envelopeBytes)
}
