name: License Checker

on:
  push:
    branches:
      - main
      - release-*
      - license
  pull_request:
    branches:
      - main
      - release-*

permissions:
  contents: write
  pull-requests: write

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check license header
        uses: apache/skywalking-eyes/header@v0.4.0
        with:
          mode: fix
          config: .github/licenserc.yml
      - name: Check dependencies license
        uses: apache/skywalking-eyes/dependency@v0.4.0
        with:
          config: .github/licenserc.yml