name: Reusable build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17, 1.18]
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go ${{ matrix.go-version }} environment
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: Run unit tests
        run: make test
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3